# Generated by Django 2.2.7 on 2019-11-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_depoimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='depoimentos/', verbose_name='Imagem'),
        ),
    ]
